### PR TITLE
Fixed WaitGroup race and added RunCloserRoutine helper

### LINKED ISSUE #19: Race condition on WaitGroup
Consider the following code:  
```
func test1(cl closer.Closer) {
    cl.Close_() // Imagine this gets called in another routine in a real use case.
    cl.CloserAddWait(1)
    go func() { defer cl.CloserDone() }()
}
```

There is a potential race here, since the WaitGroup itself is not synchronized to the current state of the closer.
One can therefore never be sure that adding to the wait group of a closer actually causes the closer to wait.

### PR DESCRIPTION
**Pull request by r0l1**
Fixed WaitGroup race and added RunCloserRoutine helper for a easy and safe way to start closer routines

Closes #19

### CODE REVIEW

File: closer_test.go [hunk 1]
```diff
@@ -566,3 +580,41 @@ func TestEndlessGrowth(t *testing.T) {
...
+
+	select {
+	case <-time.After(3 * time.Second):
+		t.Fatal("timed out")
+	case <-started:
+	}
+
+	c.Close_()
+	r.Error(t, c.CloserError())
+	r.Equal(t, c.CloserError().Error(), "error")
```
Comment (skaldesh) [inline closer_test.go]: You could use both `r.EqualError` or even better `r.ErrorIs` instead.

File: closer.go [hunk 2]
```diff
@@ -448,16 +473,31 @@ func (c *closer) CloserWaitChan(ctx context.Context) <-chan error {
 	return waitChan
 }
 
+// Implements the Closer interface.
+func (c *closer) RunCloserRoutine(f func() error) {
+	c.CloserAddWait(1)
+	go func() {
+		// CloserAddWait will also add to a closed closer. Ensure we are not in a closing state.
+		if c.IsClosing() {
```
Comment (skaldesh) [inline closer.go:481]: This is an "optimization", right? So if the closer has been closed in between the routine being scheduled, we will not run the callback.  
There is still the possibility that after the if check the closer is closed. Maybe the check can be omitted in favor of the code being more simple to read? 

! Subjective Feedback !

**Review by skaldesh — COMMENTED** [review]
I like it, simple but effective solution :+1:

File: closer_test.go (hunk 1 above)
Comment (r0l1) [reply closer_test.go]: Good catch!

File: closer.go (hunk 2 above)
Comment (r0l1) [reply closer.go:481]: We need at least one IsClosing check after `CloserAddWait`. We must ensure, that the caller did not close before calling `CloserAddWait`, because otherwise the Close call will not wait for the "WaitGroup". This should fix the "race" condition with an async close during initialization. Another approach would be to use the mutex and create private helpers.

**Review by skaldesh — APPROVED** [review]
